// <auto-generated />
using System;
using LiamellCruz_Ap1_P1.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LiamellCruz_Ap1_P1.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20241013025045_Modficacion")]
    partial class Modficacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("LiamellCruz_Ap1_P1.Models.Cobros", b =>
                {
                    b.Property<int>("CobroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeudorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<double>("Monto")
                        .HasColumnType("REAL");

                    b.HasKey("CobroId");

                    b.HasIndex("DeudorId");

                    b.ToTable("Cobro");
                });

            modelBuilder.Entity("LiamellCruz_Ap1_P1.Models.CobrosDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CobroId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ValorCobrado")
                        .HasColumnType("REAL");

                    b.HasKey("DetalleId");

                    b.HasIndex("CobroId");

                    b.HasIndex("PrestamoId");

                    b.ToTable("CobroDetalle");
                });

            modelBuilder.Entity("LiamellCruz_Ap1_P1.Models.Deudor", b =>
                {
                    b.Property<int>("DeudorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DeudorId");

                    b.ToTable("Deudor");

                    b.HasData(
                        new
                        {
                            DeudorId = 1,
                            Nombres = "liamell Cruz"
                        },
                        new
                        {
                            DeudorId = 2,
                            Nombres = "Marcos Rosario"
                        },
                        new
                        {
                            DeudorId = 3,
                            Nombres = "Josmeyli Duarte"
                        });
                });

            modelBuilder.Entity("LiamellCruz_Ap1_P1.Models.Prestamos", b =>
                {
                    b.Property<int>("PrestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeudorId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Monto")
                        .HasColumnType("REAL");

                    b.HasKey("PrestamoId");

                    b.HasIndex("DeudorId");

                    b.ToTable("Prestamo");
                });

            modelBuilder.Entity("LiamellCruz_Ap1_P1.Models.Cobros", b =>
                {
                    b.HasOne("LiamellCruz_Ap1_P1.Models.Deudor", "Deudor")
                        .WithMany()
                        .HasForeignKey("DeudorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deudor");
                });

            modelBuilder.Entity("LiamellCruz_Ap1_P1.Models.CobrosDetalle", b =>
                {
                    b.HasOne("LiamellCruz_Ap1_P1.Models.Cobros", "Cobro")
                        .WithMany("CobroDetalle")
                        .HasForeignKey("CobroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiamellCruz_Ap1_P1.Models.Prestamos", "Prestamo")
                        .WithMany()
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cobro");

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("LiamellCruz_Ap1_P1.Models.Prestamos", b =>
                {
                    b.HasOne("LiamellCruz_Ap1_P1.Models.Deudor", "Deudor")
                        .WithMany()
                        .HasForeignKey("DeudorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deudor");
                });

            modelBuilder.Entity("LiamellCruz_Ap1_P1.Models.Cobros", b =>
                {
                    b.Navigation("CobroDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
